# Generated by Django 3.0.14 on 2022-04-12 11:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('company_type', models.CharField(max_length=30, null=True)),
                ('company_specialization', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('company_logo', models.ImageField(null=True, upload_to='company_logo')),
                ('about_company', models.TextField(max_length=300, null=True)),
                ('company_site', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.CharField(max_length=100)),
                ('lkd', models.CharField(max_length=100)),
                ('git', models.CharField(max_length=100)),
                ('hacker', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.FileField(max_length=210, null=True, upload_to='')),
                ('portfolio', models.CharField(max_length=210, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
                ('emp_type', models.CharField(max_length=50)),
                ('work_name', models.CharField(max_length=100)),
                ('experience_or_time', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('salary_or_stipend', models.CharField(max_length=20)),
                ('about', ckeditor.fields.RichTextField()),
                ('min_requirement', ckeditor.fields.RichTextField()),
                ('tech_stack', models.CharField(max_length=100)),
                ('posted', models.DateField(auto_now_add=True)),
                ('number_of_vacancy', models.CharField(max_length=3)),
                ('status', models.BooleanField(default=True)),
                ('applicants', models.ManyToManyField(to='HireApp.UserProfile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HireApp.CompanyProfile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('hired', models.ManyToManyField(related_name='hired', to='HireApp.UserProfile')),
                ('resume_selected', models.ManyToManyField(related_name='resume_selected', to='HireApp.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=30)),
                ('emoji', models.CharField(max_length=30, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('selected', models.ManyToManyField(related_name='selected', to='HireApp.UserProfile')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HireApp.Work')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HireApp.CompanyProfile')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=10)),
                ('start_year', models.CharField(max_length=100, null=True)),
                ('end_year', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=20, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('start_year', models.CharField(max_length=100, null=True)),
                ('end_year', models.CharField(max_length=100, null=True)),
                ('degree', models.CharField(max_length=20, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=10)),
                ('month_name', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=100)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
