# Generated by Django 3.1.2 on 2022-02-28 17:44

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(max_length=30)),
                ('company_specialization', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('company_logo', models.ImageField(upload_to='company_logo')),
                ('about_company', models.TextField(max_length=300)),
                ('company_site', models.CharField(max_length=50)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
                ('emp_type', models.CharField(max_length=50)),
                ('work_name', models.CharField(max_length=100)),
                ('about', ckeditor.fields.RichTextField()),
                ('min_requirement', ckeditor.fields.RichTextField()),
                ('location', models.CharField(max_length=100)),
                ('experience_or_time', models.CharField(max_length=10)),
                ('tech_stack', models.CharField(max_length=100)),
                ('posted', models.DateField(auto_now_add=True)),
                ('number_of_vacancy', models.CharField(max_length=3)),
                ('status', models.BooleanField(default=True)),
                ('salary_or_stipend', models.CharField(max_length=20)),
                ('applicants', models.ManyToManyField(to='UserApp.Profile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HireApp.companyprofile')),
                ('hired', models.ManyToManyField(related_name='hired', to='UserApp.Profile')),
                ('resume_selected', models.ManyToManyField(related_name='resume_selected', to='UserApp.Profile')),
            ],
        ),
    ]
