# Generated by Django 3.0.14 on 2022-03-19 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HireApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='username',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.CharField(max_length=100)),
                ('lkd', models.CharField(max_length=100)),
                ('git', models.CharField(max_length=100)),
                ('hacker', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('college_name', models.CharField(max_length=100, null=True)),
                ('college_year', models.CharField(max_length=100, null=True)),
                ('college_branch', models.CharField(max_length=20, null=True)),
                ('resume', models.FileField(max_length=210, null=True, upload_to='')),
                ('portfolio', models.CharField(max_length=210, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=30)),
                ('emoji', models.CharField(max_length=30, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('selected', models.ManyToManyField(related_name='selected', to='HireApp.UserProfile')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HireApp.Work')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HireApp.CompanyProfile')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=10)),
                ('month_name', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=100)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='work',
            name='applicants',
            field=models.ManyToManyField(to='HireApp.UserProfile'),
        ),
        migrations.AlterField(
            model_name='work',
            name='hired',
            field=models.ManyToManyField(related_name='hired', to='HireApp.UserProfile'),
        ),
        migrations.AlterField(
            model_name='work',
            name='resume_selected',
            field=models.ManyToManyField(related_name='resume_selected', to='HireApp.UserProfile'),
        ),
    ]
