# Generated by Django 3.0.14 on 2022-04-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HireApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HireApp.RecruiterProfile'),
        ),
    ]
