# Generated by Django 3.0.14 on 2022-04-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HireApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='about_company',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_site',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
