# Generated by Django 3.0.14 on 2022-04-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HireApp', '0002_auto_20220414_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=models.CharField(max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='organisation',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
