# Generated by Django 3.0.14 on 2022-04-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HireApp', '0003_auto_20220419_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
