# Generated by Django 3.0.14 on 2022-04-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HireApp', '0004_auto_20220425_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='organisation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
