# Generated by Django 3.0.14 on 2022-03-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HireApp', '0004_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HireApp.CompanyProfile'),
        ),
    ]
