# Generated by Django 3.1.2 on 2022-04-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HireApp', '0005_auto_20220327_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='about_company',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='company_logo'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_specialization',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
