# Generated by Django 3.0.14 on 2022-04-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HireApp', '0008_auto_20220427_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(max_length=210, null=True, upload_to='resume'),
        ),
    ]
