# Generated by Django 3.1.2 on 2022-02-28 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=30)),
                ('emoji', models.CharField(max_length=30, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.CharField(max_length=100)),
                ('lkd', models.CharField(max_length=100)),
                ('git', models.CharField(max_length=100)),
                ('hacker', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=200)),
                ('college_name', models.CharField(max_length=100, null=True)),
                ('college_year', models.CharField(max_length=100, null=True)),
                ('college_branch', models.CharField(max_length=20, null=True)),
                ('resume', models.FileField(max_length=210, null=True, upload_to='')),
                ('portfolio', models.CharField(max_length=210, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=10)),
                ('month_name', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=100)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
