# Generated by Django 3.0.14 on 2022-03-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HireApp', '0002_auto_20220319_0722'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='username',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
