# Generated by Django 3.2.7 on 2022-03-27 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NotesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPrep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='InterviewPrep/Fileuploads/')),
                ('url', models.URLField(blank=True, null=True)),
                ('IsApproved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('years', models.CharField(choices=[('FirstYear', 'FirstYear'), ('SecondYear', 'SecondYear'), ('ThirdYear', 'ThirdYear'), ('FourthYear', 'FourthYear')], max_length=100)),
                ('Branch', models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ME', 'ME'), ('AG', 'AG'), ('CE', 'CE'), ('BT', 'BT')], default=None, max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='StudyMaterials/Fileuploads/')),
                ('url', models.URLField(blank=True, null=True)),
                ('IsApproved', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='interviewprep',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NotesApp.category'),
        ),
        migrations.AddField(
            model_name='interviewprep',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewprep',
            name='tags',
            field=models.ManyToManyField(to='NotesApp.Tags'),
        ),
    ]
