# Generated by Django 3.0.14 on 2022-03-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0002_auto_20220327_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterials',
            name='years',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=100),
        ),
    ]
